### ISSUE TITLE
Go unit tests fail with cannot use result.SubtestName (type *string) as type string in argument to serializeStrings

### ISSUE THREAD

**Issue by clopez** [web-platform-tests/wpt-metadata#37] opened 2019-10-25 16:52 UTC
I'm trying to run the unit tests of this repository but I'm unable.
this is the failure I get:

```
$ cd wpt-metadata
$ go get -t ./...
$ go test -v ./...
# _/home/clopez/webkit/wpt-metadata [_/home/clopez/webkit/wpt-metadata.test]
./parse_test.go:68:54: cannot use result.SubtestName (type *string) as type string in argument to serializeStrings
FAIL	_/home/clopez/webkit/wpt-metadata [build failed]
=== RUN   TestParseMetadataFromGZip_Success
--- PASS: TestParseMetadataFromGZip_Success (0.00s)
PASS
ok  	_/home/clopez/webkit/wpt-metadata/util	(cached)

```

I tried removing also my whole ```~/go``` directory and running again ```go get -t ./...``` to install the dependencies from scratch. Didn't helped

Is this something that you can reproduce? Any idea of how I can fix it?

//cc @foolip

**Comment by clopez** [comment] 2019-10-25 16:53
BTW, my Go version is
```
$ go version
go version go1.11.6 linux/amd64
```

**Comment by stephenmcgruer** [comment] 2019-10-25 18:13
I am able to reproduce:

```
smcgruer@stiglet2:~/github/wpt-metadata$ go get -t ./...
smcgruer@stiglet2:~/github/wpt-metadata$ go test -v ./...
# _/usr/local/google/home/smcgruer/github/wpt-metadata [_/usr/local/google/home/smcgruer/github/wpt-metadata.test]
./parse_test.go:68:54: cannot use result.SubtestName (type *string) as type string in argument to serializeStrings
FAIL	_/usr/local/google/home/smcgruer/github/wpt-metadata [build failed]
=== RUN   TestParseMetadataFromGZip_Success
--- PASS: TestParseMetadataFromGZip_Success (0.00s)
PASS
ok  	_/usr/local/google/home/smcgruer/github/wpt-metadata/util	0.065s
FAIL
smcgruer@stiglet2:~/github/wpt-metadata$ go version
go version go1.13 linux/amd64
```

@KyleJu can you take a look?

**Comment by stephenmcgruer** [comment] 2019-10-25 18:19
Looks like this was probably broken by https://github.com/web-platform-tests/wpt.fyi/pull/1525, and I assume we aren't versioning the import from wpt.fyi (cc @Hexcles who knows more than me about versioning), so it quietly broke this when it landed.

**Comment by stephenmcgruer** [comment] 2019-10-28 17:11
@KyleJu @Hexcles What is our plan to avoid this happening again in the future?

**Comment by KyleJu** [comment] 2019-10-28 17:26
Both test_paths_test.go and parse_test.go rely on the metadata data model in the wpt.fyi shared class. We can remove wpt.fyi dependencies instead. Probably a better approach than enforcing a versioning

**Comment by stephenmcgruer** [comment] 2021-01-26 20:52
We now have versioning in wpt.fyi, so this shouldnt break us too much anymore.

**Closed by stephenmcgruer** 2021-01-26 20:52 UTC
